name: cassowary
version: 0.2.0
description: Cassowary Constraint Solving Toolkit
author: Chromium Authors <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/cassowary
environment:
  sdk: '>=1.21.0 <2.0.0'
dev_dependencies:
  test: ^0.12.18
  dart_coveralls: ^0.4.0
