name: flutter
version: 0.0.21
author: Flutter Authors <flutter-dev@googlegroups.com>
description: A framework for writing Flutter applications
homepage: http://flutter.io

dependencies:
  collection: '>=1.4.0 <2.0.0'
  intl: '>=0.12.4+2 <0.13.0'
  vector_math: '>=2.0.3 <3.0.0'

  crypto: '>=1.1.1 <3.0.0'

  meta: ^0.12.0

  sky_engine:
    path: ../../bin/cache/pkg/sky_engine
  sky_services:
    path: ../../bin/cache/pkg/sky_services

dev_dependencies:
  flutter_test:
    path: ../flutter_test

environment:
  sdk: '>=1.16.0 <2.0.0'
