name: flutter
version: 0.0.21
author: Flutter Authors <flutter-dev@googlegroups.com>
description: A framework for writing Flutter applications
homepage: http://flutter.io

dependencies:
  collection: '>=1.1.3 <2.0.0'
  intl: '>=0.12.4+2 <0.13.0'
  material_design_icons: '>=0.0.3 <0.1.0'
  sky_engine: 0.0.89
  sky_services: 0.0.89
  vector_math: '>=1.4.5 <2.0.0'
  quiver: '>=0.21.4 <0.22.0'

  # See the comment in flutter_tools' pubspec.yaml. We have to pin it
  # here also because sky_services depends on mojo_sdk which depends
  # on test.
  test: 0.12.6+1

  cassowary:
    path: ../cassowary
  newton:
    path: ../newton

dev_dependencies:
  flutter_test:
    path: ../flutter_test
  stocks:
    path: ../../examples/stocks

environment:
  sdk: '>=1.12.0 <2.0.0'
