name: sky
version: 0.0.47
author: Chromium Authors <sky-dev@googlegroups.com>
description: A framework for writing Flutter applications
homepage: http://flutter.io
dependencies:
  cassowary: ^0.1.7
  material_design_icons: ^0.0.3
  mojo_services: 0.0.23
  mojo: 0.0.23
  newton: ^0.1.2
  sky_engine: ^0.0.24
  sky_services: ^0.0.24
  sky_tools: ^0.0.12
  vector_math: ^1.4.3
  intl: ^0.12.4+2
environment:
  sdk: '>=1.12.0 <2.0.0'
