name: sky
version: 0.0.22
author: Chromium Authors <sky-dev@googlegroups.com>
description: A framework for writing Sky applications
homepage: https://github.com/domokit/sky_engine/tree/master/sky/sdk
dependencies:
  cassowary: ^0.1.7
  material_design_icons: ^0.0.2
  mojo_services: ^0.0.15
  mojo: ^0.0.17
  mojom: ^0.0.17
  newton: ^0.1.0
  sky_engine: ^0.0.1
  sky_services: ^0.0.1
  sky_tools: ^0.0.3
  vector_math: ^1.4.3
environment:
  sdk: '>=1.8.0 <2.0.0'
