name: flutter
version: 0.0.21
author: Flutter Authors <flutter-dev@googlegroups.com>
description: A framework for writing Flutter applications
homepage: http://flutter.io

dependencies:
  collection: '>=1.4.0 <2.0.0'
  intl: '>=0.12.4+2 <0.13.0'
  vector_math: '>=1.4.5 <2.0.0'

  # We need to pin crypto because archive can't handle larger numbers.
  crypto: 0.9.2

  sky_engine:
    path: ../../bin/cache/pkg/sky_engine
  sky_services:
    path: ../../bin/cache/pkg/sky_services

  cassowary:
    path: ../cassowary
  newton:
    path: ../newton

dev_dependencies:
  flutter_test:
    path: ../flutter_test
  stocks: # for the benchmarks
    path: ../../examples/stocks

environment:
  sdk: '>=1.12.0 <2.0.0'
